#!/usr/bin/env python3
"""
Generate HeyGen curl commands from the HeyGen Ready Script section.
Creates one curl command per chapter with properly escaped content.
"""

import re
import sys
from pathlib import Path


def escape_for_bash_single_quotes(text):
    """Escape text for use inside bash single quotes."""
    # Replace ' with '\''
    return text.replace("'", "'\\''")


def escape_quotes_in_json(text):
    """Escape double quotes for JSON strings."""
    return text.replace('"', '\\"')


def parse_heygen_section(script_path):
    """Parse the HeyGen section from a generated script file."""
    with open(script_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the HeyGen section
    heygen_match = re.search(r'# 🎬 HEYGEN READY SCRIPT\s*={70,}\s*(.+?)(?:\*Generated by LineDrive|$)',
                             content, re.DOTALL)

    if not heygen_match:
        print("❌ Could not find HeyGen Ready Script section")
        return None, None

    heygen_content = heygen_match.group(1).strip()

    # Extract script title from the beginning of the file
    title_match = re.search(r'^#\s+(.+?)$', content, re.MULTILINE)
    script_title = title_match.group(1).strip() if title_match else "AI Video"

    # Split by headings
    chapters = []

    # First chapter is everything before the first "Heading:"
    intro_match = re.search(r'^(.+?)(?=\nHeading:)', heygen_content, re.DOTALL)
    if intro_match:
        intro_text = intro_match.group(1).strip()
        # Clean up line wrapping
        intro_text = re.sub(r'\s*\n\s*', ' ', intro_text)
        intro_text = re.sub(r'\s{2,}', ' ', intro_text)
        chapters.append({
            'title': script_title,
            'content': intro_text
        })

    # Find all other chapters
    chapter_pattern = r'Heading:\s+(.+?)\n\n(.+?)(?=\nHeading:|$)'
    for match in re.finditer(chapter_pattern, heygen_content, re.DOTALL):
        chapter_title = match.group(1).strip()
        chapter_content = match.group(2).strip()

        # Clean up line wrapping
        chapter_content = re.sub(r'\s*\n\s*', ' ', chapter_content)
        chapter_content = re.sub(r'\s{2,}', ' ', chapter_content)

        chapters.append({
            'title': f"{script_title} - {chapter_title}",
            'content': chapter_content
        })

    return script_title, chapters


def generate_curl_command(chapter_title, chapter_content, api_key, template_id):
    """Generate a curl command for a chapter."""
    # Escape the content for bash single quotes
    escaped_content = escape_for_bash_single_quotes(chapter_content)
    escaped_title = escape_for_bash_single_quotes(chapter_title)

    curl_cmd = f"""curl --request POST \\
     --url 'https://api.heygen.com/v2/template/{template_id}/generate' \\
     --header 'accept: application/json' \\
     --header 'content-type: application/json' \\
     --header 'x-api-key: {api_key}' \\
     --data '{{
  "caption": false,
  "title": "{escaped_title}",
  "variables": {{
    "script": {{
      "name": "script",
      "type": "text",
      "properties": {{
        "content": "{escaped_content}"
      }}
    }}
  }}
}}'"""

    return curl_cmd


def main():
    # Configuration
    API_KEY = "ZmExMjJmMTY2NmZmNGI4NDhiYjM3ZWViYzgyYmE3ZWItMTc1MzQ4OTA1Mw=="
    TEMPLATE_ID = "92c09f8e9a1c4f078f7ae53886b7ad80"

    # Check for command line argument
    if len(sys.argv) > 1:
        script_path = Path(sys.argv[1])
        if not script_path.exists():
            print(f"❌ File not found: {script_path}")
            return 1
    else:
        # Find the most recent script file
        scripts_dir = Path.home() / "Dev" / "Scripts"
        script_files = sorted(scripts_dir.glob(
            "*_20251017_*.md"), reverse=True)

        if not script_files:
            print("❌ No script files found for today")
            return 1

        script_path = script_files[0]

    print(f"📄 Processing: {script_path.name}\n")

    # Parse the HeyGen section
    script_title, chapters = parse_heygen_section(script_path)

    if not chapters:
        print("❌ No chapters found in HeyGen section")
        return 1

    print(f"✅ Found {len(chapters)} chapters\n")
    print("=" * 80)

    # Generate curl commands
    output_lines = []
    output_lines.append("#!/bin/bash")
    output_lines.append("# HeyGen API curl commands - Generated from script")
    output_lines.append(f"# Script: {script_title}")
    output_lines.append(f"# Generated: {Path(script_path).stem}")
    output_lines.append("")

    for i, chapter in enumerate(chapters, 1):
        print(f"\n{'='*80}")
        print(f"Chapter {i}: {chapter['title']}")
        print(f"Content length: {len(chapter['content'])} characters")
        print(f"{'='*80}\n")

        curl_cmd = generate_curl_command(
            chapter['title'],
            chapter['content'],
            API_KEY,
            TEMPLATE_ID
        )

        print(curl_cmd)
        print("\n")

        # Add to output file with separation
        output_lines.append(f"# Chapter {i}: {chapter['title']}")
        output_lines.append(curl_cmd)
        output_lines.append("")
        output_lines.append("")

    # Save to file
    output_file = Path.cwd() / "heygen_all_chapters.sh"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output_lines))

    print(f"\n{'='*80}")
    print(f"✅ Generated {len(chapters)} curl commands")
    print(f"📄 Saved to: {output_file}")
    print(f"{'='*80}\n")
    print("To run all chapters:")
    print(f"  bash {output_file}")
    print("\nTo run individual chapters, copy/paste the command from the output above")

    return 0


if __name__ == "__main__":
    sys.exit(main())
