"""
Quote and Statistics Agent - Integration Example

This file demonstrates how the Quote and Statistics Agent will be integrated
into the full script workflow. This is just an EXAMPLE - NOT the final integration.

Integration Point: RIGHT AFTER Script Writer/Review, BEFORE B-roll/thumbnails

Workflow Order:
1. Script Topic Assistant
2. Script Writer (chapter by chapter)
3. Script Review (chapter by chapter)
4. ✨ Quote & Statistics Agent (NEW) ✨
5. B-roll Search Terms
6. B-roll Images
7. HeyGen Section
8. Demo Packages
9. Flow Analysis (if checked)
10. YouTube Upload Details (if checked)
11. Thumbnails (if checked)

Author: Christian Thilmany
Created: November 21, 2025
"""


def integrate_quotes_and_statistics_into_workflow(
    script_content: str,
    script_title: str,
    target_audience: str,
    tone: str,
    checkboxes: dict
) -> tuple:
    """
    Example of how to integrate Quote & Statistics Agent into the workflow.

    Args:
        script_content: The completed script from Script Writer/Review
        script_title: Title of the video
        target_audience: Target audience level
        tone: Desired tone
        checkboxes: Dict of which optional agents to run

    Returns:
        tuple: (enhanced_script, quotes_and_stats_section)
    """
    from linedrive_azure.agents.quote_and_statistics_agent_client import (
        QuoteAndStatisticsAgentClient
    )

    # Check if user wants quotes and statistics
    if not checkboxes.get("quotes_and_statistics", False):
        print("   ⏭️  Skipping Quote & Statistics Agent (not checked)")
        return script_content, None

    print("\n" + "=" * 80)
    print("🎬 STEP 4: Quote & Statistics Generation")
    print("=" * 80)

    try:
        # Initialize the Quote & Statistics Agent
        quotes_agent = QuoteAndStatisticsAgentClient()

        # Extract topic from script title or first chapter
        topic = script_title

        # Generate quotes and statistics
        result = quotes_agent.generate_quotes_and_statistics(
            topic=topic,
            script_title=script_title,
            target_audience=target_audience,
            tone=tone,
            additional_context=f"This script is {len(script_content)} characters long",
            timeout=120
        )

        if result["success"]:
            quotes_count = result.get("quotes_count", 0)
            stats_count = result.get("statistics_count", 0)
            print(
                f"✅ Generated {quotes_count} quotes and {stats_count} statistics")

            # Format the quotes and statistics section
            quotes_section = _format_quotes_section(result)

            # Insert quotes section BEFORE Chapter 1 in the script
            enhanced_script = _insert_quotes_before_chapters(
                script_content,
                quotes_section
            )

            print(f"✅ Quotes and statistics section added to script")
            return enhanced_script, quotes_section

        else:
            error = result.get("error", "Unknown error")
            print(f"⚠️  Quote & Statistics Agent failed: {error}")
            print("   Continuing without quotes and statistics...")
            return script_content, None

    except Exception as e:
        print(f"⚠️  Exception in Quote & Statistics Agent: {e}")
        print("   Continuing without quotes and statistics...")
        return script_content, None


def _format_quotes_section(result: dict) -> str:
    """
    Format the quotes and statistics into a nice section for the script.

    Args:
        result: The result dict from the Quote & Statistics Agent

    Returns:
        str: Formatted markdown section
    """
    section = "\n" + "=" * 80 + "\n"
    section += "## 📊 SUPPORTING RESEARCH & EXPERT PERSPECTIVES\n"
    section += "=" * 80 + "\n\n"
    section += "_The following quotes and statistics were generated by AI to provide "
    section += "credible, recent data for this video. You may choose to integrate "
    section += "these into your script or use them as reference material._\n\n"

    # Add the full agent response (which includes formatting)
    section += result.get("raw_response", "")

    section += "\n" + "=" * 80 + "\n"
    section += "## 🎬 SCRIPT CONTENT\n"
    section += "=" * 80 + "\n\n"

    return section


def _insert_quotes_before_chapters(script_content: str, quotes_section: str) -> str:
    """
    Insert the quotes and statistics section BEFORE Chapter 1 in the script.

    Args:
        script_content: The original script
        quotes_section: The formatted quotes section

    Returns:
        str: Enhanced script with quotes section
    """
    # Find where Chapter 1 starts
    # Look for patterns like "## Chapter 1" or "# Chapter 1"
    import re

    # Try to find Chapter 1 marker
    chapter_1_patterns = [
        r'^## Chapter 1',
        r'^# Chapter 1',
        r'^Chapter 1:',
        r'^## 1\.',
        r'^# 1\.'
    ]

    chapter_1_pos = -1
    for pattern in chapter_1_patterns:
        match = re.search(pattern, script_content, re.MULTILINE)
        if match:
            chapter_1_pos = match.start()
            break

    # If we found Chapter 1, insert before it
    if chapter_1_pos > 0:
        # Insert quotes section before Chapter 1
        enhanced_script = (
            script_content[:chapter_1_pos] +
            quotes_section +
            script_content[chapter_1_pos:]
        )
        return enhanced_script
    else:
        # If Chapter 1 not found, append to beginning after any existing headers
        # This is a fallback - try to place after title but before content
        lines = script_content.split('\n')
        insert_pos = 0

        # Skip past title and any metadata
        for i, line in enumerate(lines):
            if line.strip() and not line.startswith('#') and not line.startswith('='):
                insert_pos = i
                break

        lines.insert(insert_pos, quotes_section)
        return '\n'.join(lines)


# Example of web_gui.py integration
def example_web_gui_integration():
    """
    Example of how this would be integrated into web_gui.py

    This is pseudocode showing the integration point.
    """

    # ... (existing code for script creation) ...

    # After Script Writer and Review complete:
    # script_content = [result from Script Writer + Review]

    # NEW: Add Quote & Statistics Agent
    if checkboxes.get("quotes_and_statistics", False):
        progress = 58  # After review (55%), before B-roll (60%)
        send_update("📊 Generating quotes and statistics...", progress)

        enhanced_script, quotes_section = integrate_quotes_and_statistics_into_workflow(
            script_content=script_content,
            script_title=topic,
            target_audience=audience,
            tone=tone,
            checkboxes=checkboxes
        )

        if quotes_section:
            script_content = enhanced_script
            send_update("✅ Quotes and statistics added to script", 58)

    # Continue with existing workflow (B-roll, etc.)
    # ...


# Example checkbox addition for web GUI
def example_checkbox_html():
    """
    Example HTML checkbox to add to the web GUI form.

    Add this to templates/index.html in the checkboxes section.
    """
    html = """
    <div class="checkbox-item" title="Generate 3 expert quotes and 3 statistics">
        <input type="checkbox" id="quotes_and_statistics" name="quotes_and_statistics">
        <label for="quotes_and_statistics">
            📊 Quotes & Statistics
            <span class="tooltip">Adds recent expert quotes and research statistics</span>
        </label>
    </div>
    """
    return html


# Example progress mapping
PROGRESS_MAP_WITH_QUOTES = {
    "Topic Enhancement": 5,
    "Chapter Planning": 21,
    "Script Writing Start": 26,
    "Script Writing End": 55,
    "Review Complete": 55,
    "Quotes & Statistics": 58,  # NEW step
    "B-roll Search Terms": 60,
    "B-roll Images": 65,
    "HeyGen Section": 70,
    "Demo Packages": 75,
    "Flow Analysis": 80,
    "YouTube Details": 85,
    "Thumbnails": 90,
    "Complete": 100
}


if __name__ == "__main__":
    print("=" * 80)
    print("📚 QUOTE & STATISTICS AGENT - INTEGRATION EXAMPLE")
    print("=" * 80)
    print()
    print("This file demonstrates how the Quote & Statistics Agent")
    print("will be integrated into the full script workflow.")
    print()
    print("Integration Point: RIGHT AFTER Script Writer/Review")
    print("                   BEFORE B-roll/thumbnails")
    print()
    print("Files that will need to be modified:")
    print("1. web_gui.py - Add agent call after review step")
    print("2. templates/index.html - Add checkbox for quotes & statistics")
    print("3. enhanced_autogen_system.py - Add to 4-agent workflow (optional)")
    print()
    print("Progress mapping:")
    for step, progress in PROGRESS_MAP_WITH_QUOTES.items():
        marker = "✨" if step == "Quotes & Statistics" else "  "
        print(f"{marker} {progress:3d}% - {step}")
    print()
    print("=" * 80)
